USE petsdb;
DROP TABLE user_roles;
DROP TABLE ptts_roles;
DROP TABLE ptts_adoptions;
DROP TABLE ptts_searches;
DROP TABLE ptts_pets;
DROP TABLE ptts_breeds;
DROP TABLE ptts_species;
DROP TABLE ptts_shelters;
DROP TABLE ptts_users;