INSERT INTO ptts_species(id, description, state) values (1, 'Perro',1);
INSERT INTO ptts_species(id, description, state) values (2, 'Gato',1);


INSERT INTO ptts_breeds(id, description,state,species_id) values ( 1,'Affenpinscher', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 2,'Afghan Hound', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 3,'Africanis', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 4,'Aidi', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 5,'Airedale Terrier', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 6,'Akbash', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 7,'Akita', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 8,'Aksaray Malaklisi', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 9,'Alano Español', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 10,'Alapaha Blue Blood Bulldog', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 11,'Alaskan Husky', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 12,'Alaskan Klee Kai', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 13,'Alaskan Malamute', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 14,'Alopekis', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 15,'Alpine Dachsbracke', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 16,'American Bulldog', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 17,'American Bully', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 18,'American Cocker Spaniel', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 19,'American English Coonhound', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 20,'American Eskimo Dog', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 21,'American Foxhound', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 22,'American Hairless Terrier', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 23,'American Leopard Hound', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 24,'American Pit Bull Terrier', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 25,'American Staffordshire Terrier', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 26,'American Water Spaniel', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 27,'Anglo-Français de Petite Vénerie', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 28,'Appenzeller Sennenhund', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 29,'Ariège Pointer', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 30,'Ariégeois', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 31,'Argentine Pila', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 32,'Armant', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 33,'Armenian Gampr', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 34,'Artois Hound', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 35,'Australian Cattle Dog', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 36,'Australian Kelpie', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 37,'Australian Shepherd', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 38,'Australian Silky Terrier', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 39,'Australian Stumpy Tail Cattle Dog', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 40,'Australian Terrier', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 41,'Austrian Black and Tan Hound', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 42,'Austrian Pinscher', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 43,'Azawakh', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 44,'Bắc Hà', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 45,'Bakharwal', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 46,'Banjara Hound', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 47,'Bankhar Dog', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 48,'Barak hound', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 49,'Barbado da Terceira', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 50,'Barbet', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 51,'Basenji', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 52,'Basque Shepherd Dog', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 53,'Basset Artésien Normand', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 54,'Basset Bleu de Gascogne', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 55,'Basset Fauve de Bretagne', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 56,'Basset Hound', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 57,'Bavarian Mountain Hound', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 58,'Beagle', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 59,'Beagle-Harrier', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 60,'Bearded Collie', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 61,'Beauceron', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 62,'Bedlington Terrier', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 63,'Belgian Shepherd', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 64,'Bergamasco Shepherd', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 65,'Berger Picard', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 66,'Bernese Mountain Dog', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 67,'Bichon Frisé', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 68,'Biewer Terrier', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 69,'Billy', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 70,'Black and Tan Coonhound', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 71,'Black and Tan Terrier', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 72,'Black Norwegian Elkhound', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 73,'Black Russian Terrier', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 74,'Black Mouth Cur', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 75,'Bloodhound', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 76,'Blue Lacy', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 77,'Blue Picardy Spaniel', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 78,'Bluetick Coonhound', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 79,'Boerboel', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 80,'Bohemian Shepherd', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 81,'Bolognese', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 82,'Border Collie', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 83,'Border Terrier', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 84,'Borzoi', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 85,'Boston Terrier', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 86,'Bouvier des Ardennes', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 87,'Bouvier des Flandres', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 88,'Boxer', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 89,'Boykin Spaniel', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 90,'Bracco Italiano', 1, 1);


INSERT INTO ptts_breeds(id, description,state,species_id) values ( 91,'Braque dAuvergne', 1, 1);

INSERT INTO ptts_breeds(id, description,state,species_id) values ( 92,'Braque du Bourbonnais', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 93,'Braque Français', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 94,'Braque Saint-Germain', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 95,'Brazilian Terrier', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 96,'Briard', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 97,'Briquet de Provence', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 98,'Briquet Griffon Vendéen', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 99,'Brittany', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 100,'Broholmer', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 101,'Bruno Jura Hound', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 102,'Bucovina Shepherd Dog', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 103,'Bulgarian Hound', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 104,'Bulgarian Scenthound', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 105,'Bull Arab', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 106,'Bull Terrier', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 107,'Bulldog', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 108,'Bullmastiff', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 109,'Bully Kutta', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 110,'Burgos Pointer', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 111,'Ca Mè Mallorquí', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 112,'Ca de Bou', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 113,'Ca Rater Mallorquí', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 114,'Cairn Terrier', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 115,'Calupoh', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 116,'Campeiro Bulldog', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 117,'Can de Chira', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 118,'Can de Palleiro', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 119,'Canaan Dog', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 120,'Canadian Eskimo Dog', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 121,'Cane Corso', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 122,'Cane di Oropa', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 123,'Cane Paratore', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 124,'Cantabrian Water Dog', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 125,'Cão de Gado Transmontano', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 126,'Cardigan Welsh Corgi', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 127,'Carea Leonés', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 128,'Carolina Dog', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 129,'Carpathian Shepherd Dog', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 130,'Castro Laboreiro Dog', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 131,'Catahoula Leopard Dog', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 132,'Catalan Sheepdog', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 133,'Caucasian Shepherd Dog', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 134,'Cavalier King Charles Spaniel', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 135,'Central Asian Shepherd Dog', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 136,'Český fousek', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 137,'Český strakatý pes', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 138,'Cesky Terrier', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 139,'Chesapeake Bay Retriever', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 140,'Chien Français Blanc et Noir', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 141,'Chien Français Blanc et Orange', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 142,'Chien Français Tricolore', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 143,'Chihuahua', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 144,'Chilean Terrier', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 145,'Chinese Crested Dog', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 146,'Chinook', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 147,'Chippiparai', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 148,'Chongqing', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 149,'Chortai', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 150,'Chow Chow', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 151,'Chukotka sled dog', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 152,'Cimarrón Uruguayo', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 153,'Cirneco dellEtna', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 154,'Clumber Spaniel', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 155,'Colombian Fino Hound', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 156,'Continental bulldog', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 157,'Corsican Dog', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 158,'Coton de Tulear', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 159,'Cretan Hound', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 160,'Croatian Sheepdog', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 161,'Curly-coated Retriever', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 162,'Czechoslovakian Wolfdog', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 163,'Dachshund', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 164,'Dalmatian', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 165,'Dandie Dinmont Terrier', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 166,'Danish Spitz', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 167,'Danish–Swedish Farmdog', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 168,'Denmark Feist', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 169,'Dikkulak', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 170,'Dingo ', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 171,'Dobermann', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 172,'Dogo Argentino', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 173,'Dogo Sardesco', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 174,'Dogue Brasileiro', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 175,'Dogue de Bordeaux', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 176,'Donggyeongi', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 177,'Drentse Patrijshond', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 178,'Drever', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 179,'Dunker', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 180,'Dutch Shepherd', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 181,'Dutch Smoushond', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 182,'East Siberian Laika', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 183,'East European Shepherd', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 184,'Ecuadorian Hairless Dog', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 185,'English Cocker Spaniel', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 186,'English Foxhound', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 187,'English Mastiff', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 188,'English Setter', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 189,'English Shepherd', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 190,'English Springer Spaniel', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 191,'English Toy Terrier (Black & Tan)', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 192,'Entlebucher Mountain Dog', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 193,'Erbi Txakur', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 194,'Estonian Hound', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 195,'Estrela Mountain Dog', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 196,'Eurasier', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 197,'Faroese Sheepdog', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 198,'Field Spaniel', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 199,'Fila Brasileiro', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 200,'Finnish Hound', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 201,'Finnish Lapphund', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 202,'Finnish Spitz', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 203,'Flat-coated Retriever', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 204,'Florida Brown Dog a/k/a Florida Cracker Cur', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 205,'French Bulldog', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 206,'French Spaniel', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 207,'Galgo Español', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 208,'Gascon Saintongeois', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 209,'Gaucho sheepdog', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 210,'Georgian Shepherd', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 211,'German Hound', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 212,'German Longhaired Pointer', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 213,'German Pinscher', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 214,'German Roughhaired Pointer', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 215,'German Shepherd', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 216,'German Shorthaired Pointer', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 217,'German Spaniel', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 218,'German Spitz', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 219,'German Wirehaired Pointer', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 220,'Giant Schnauzer', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 221,'Glen of Imaal Terrier', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 222,'Golden Retriever', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 223,'Gończy Polski', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 224,'Gordon Setter', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 225,'Grand Anglo-Français Blanc et Noir', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 226,'Grand Anglo-Français Blanc et Orange', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 227,'Grand Anglo-Français Tricolore', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 228,'Grand Basset Griffon Vendéen', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 229,'Grand Bleu de Gascogne', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 230,'Grand Griffon Vendéen', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 231,'Great Dane', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 232,'Greater Swiss Mountain Dog', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 233,'Greek Harehound', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 234,'Greek Shepherd', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 235,'Greenland Dog', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 236,'Greyhound', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 237,'Griffon Bleu de Gascogne', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 238,'Griffon Bruxellois', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 239,'Griffon Fauve de Bretagne', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 240,'Griffon Nivernais', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 241,'Guatemalan Dogo', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 242,'Gull Dong', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 243,'Gull Terrier', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 244,'Hällefors Elkhound', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 245,'Halden Hound', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 246,'Hamiltonstövare', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 247,'Hanover Hound', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 248,'Harrier', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 249,'Havanese', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 250,'Himalayan Sheepdog', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 251,'Hmong bobtail dog', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 252,'Hokkaido', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 253,'Hovawart', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 254,'Huntaway', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 255,'Hygen Hound', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 256,'Ibizan Hound', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 257,'Icelandic Sheepdog', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 258,'Indian pariah dog', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 259,'Indian Spitz', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 260,'Irish Red and White Setter', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 261,'Irish Setter', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 262,'Irish Terrier', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 263,'Irish Water Spaniel', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 264,'Irish Wolfhound', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 265,'Istrian Coarse-haired Hound', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 266,'Istrian Shorthaired Hound', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 267,'Italian Greyhound', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 268,'Jack Russell Terrier', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 269,'Jagdterrier', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 270,'Jämthund', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 271,'Japanese Chin', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 272,'Japanese Spitz', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 273,'Japanese Terrier', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 274,'Jeju', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 275,'Jindo', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 276,'Jonangi', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 277,'Kai Ken', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 278,'Kaikadi', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 279,'Kamchatka Sled Dog', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 280,'Kangal Shepherd Dog', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 281,'Kanni', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 282,'Karakachan', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 283,'Karelian Bear Dog', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 284,'Karelo-Finnish Laika', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 285,'Kars', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 286,'Karst Shepherd', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 287,'Keeshond', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 288,'Kerry Beagle', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 289,'Kerry Blue Terrier', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 290,'Khala', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 291,'King Charles Spaniel', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 292,'King Shepherd', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 293,'Kintamani', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 294,'Kishu', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 295,'Kokoni', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 296,'Kombai', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 297,'Komondor', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 298,'Kooikerhondje', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 299,'Koolie', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 300,'Kromfohrländer', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 301,'Kuchi', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 302,'Kunming', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 303,'Kurdish Mastiff', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 304,'Kuvasz', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 305,'Labrador Retriever', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 306,'Lagotto Romagnolo', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 307,'Lài', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 308,'Lakeland Terrier', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 309,'Lancashire Heeler', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 310,'Landseer', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 311,'Lapponian Herder', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 312,'Large Münsterländer', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 313,'Leonberger', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 314,'Levriero Sardo', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 315,'Lhasa Apso', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 316,'Liangshan Dog', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 317,'Lithuanian Hound', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 318,'Lobito Herreño', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 319,'Löwchen', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 320,'Lucas Terrier', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 321,'Lupo Italiano', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 322,'Mackenzie River Husky', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 323,'Magyar Agár', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 324,'Mahratta Hound', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 325,'Majorca Shepherd Dog', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 326,'Maltese', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 327,'Manchester Terrier', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 328,'Maneto', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 329,'Markiesje', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 330,'Maremmano-Abruzzese Sheepdog', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 331,'McNab', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 332,'Miniature American Shepherd', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 333,'Miniature Bull Terrier', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 334,'Miniature Fox Terrier', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 335,'Miniature Pinscher', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 336,'Miniature Schnauzer', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 337,'Molossus of Epirus', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 338,'Mongrel', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 339,'Montenegrin Mountain Hound', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 340,'Moscow Watchdog', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 341,'Mountain Cur', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 342,'Mountain Feist', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 343,'Mudhol Hound', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 344,'Mudi', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 345,'Neapolitan Mastiff', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 346,'Nenets Herding Laika', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 347,'New Guinea singing dog', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 348,'New Zealand Heading Dog', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 349,'Newfoundland', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 350,'Norfolk Terrier', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 351,'Norrbottenspets', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 352,'Northern Inuit Dog', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 353,'Norwegian Buhund', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 354,'Norwegian Elkhound', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 355,'Norwegian Lundehund', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 356,'Norwich Terrier', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 357,'Nova Scotia Duck Tolling Retriever', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 358,'Nureongi', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 359,'Old Danish Pointer', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 360,'Old English Sheepdog', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 361,'Olde English Bulldogge', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 362,'Otterhound', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 363,'Pachón Navarro', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 364,'Pampas Deerhound', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 365,'Papillon', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 366,'Parson Russell Terrier', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 367,'Pastor Garafiano', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 368,'Pastore della Lessinia e del Lagorai', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 369,'Patagonian Sheepdog', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 370,'Patterdale Terrier', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 371,'Pekingese', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 372,'Pembroke Welsh Corgi', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 373,'Perdigueiro Galego', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 374,'Perro Majorero', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 375,'Peruvian Hairless Dog', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 376,'Petit Basset Griffon Vendéen', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 377,'Petit Bleu de Gascogne', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 378,'Phalène', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 379,'Pharaoh Hound', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 380,'Phu Quoc Ridgeback', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 381,'Picardy Spaniel', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 382,'Plummer Terrier', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 383,'Plott Hound', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 384,'Podenco Andaluz', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 385,'Podenco Canario', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 386,'Podenco Valenciano', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 387,'Pointer', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 388,'Poitevin', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 389,'Polish Greyhound', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 390,'Polish Hound', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 391,'Polish Lowland Sheepdog', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 392,'Pomeranian', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 393,'Pont-Audemer Spaniel', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 394,'Poodle', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 395,'Porcelaine', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 396,'Portuguese Podengo', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 397,'Portuguese Pointer', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 398,'Portuguese Sheepdog', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 399,'Portuguese Water Dog', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 400,'Posavac Hound', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 401,'Pražský Krysařík', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 402,'Presa Canario', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 403,'Pudelpointer', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 404,'Pug', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 405,'Puli', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 406,'Pumi', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 407,'Pungsan', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 408,'Pyrenean Mastiff', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 409,'Pyrenean Mountain Dog', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 410,'Pyrenean Sheepdog', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 411,'Rafeiro do Alentejo', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 412,'Rajapalayam', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 413,'Rampur Greyhound', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 414,'Rastreador Brasileiro', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 415,'Rat Terrier', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 416,'Ratonero Bodeguero Andaluz', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 417,'Ratonero Murciano', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 418,'Redbone Coonhound', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 419,'Rhodesian Ridgeback', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 420,'Rize Koyun', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 421,'Romanian Mioritic Shepherd Dog', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 422,'Romanian Raven Shepherd Dog', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 423,'Rottweiler', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 424,'Rough Collie', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 425,'Russian Spaniel', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 426,'Russkiy Toy', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 427,'Russo-European Laika', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 428,'Ryukyu', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 429,'Saarloos wolfdog', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 430,'Sabueso Español', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 431,'Saint Miguel Cattle Dog', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 432,'Saint-Usuge Spaniel', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 433,'Sakhalin Husky', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 434,'Saluki', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 435,'Samoyed', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 436,'Sapsali', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 437,'Sarabi', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 438,'Sardinian Shepherd Dog', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 439,'Šarplaninac', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 440,'Schapendoes', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 441,'Schillerstövare', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 442,'Schipperke', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 443,'Schweizer Laufhund', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 444,'Schweizerischer Niederlaufhund', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 445,'Scottish Deerhound', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 446,'Scottish Terrier', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 447,'Sealyham Terrier', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 448,'Segugio dell Appennino', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 449,'Segugio Italiano', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 450,'Segugio Maremmano', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 451,'Serbian Hound', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 452,'Serbian Tricolour Hound', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 453,'Serrano Bulldog', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 454,'Shar Pei', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 455,'Shetland Sheepdog', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 456,'Shiba Inu', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 457,'Shih Tzu', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 458,'Shikoku', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 459,'Shiloh Shepherd', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 460,'Siberian Husky', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 461,'Silken Windhound', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 462,'Sinhala Hound', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 463,'Skye Terrier', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 464,'Sloughi', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 465,'Slovak Rough-haired Pointer', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 466,'Slovak Cuvac', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 467,'Slovenský kopov', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 468,'Smaland Hound', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 469,'Small Münsterländer', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 470,'Smithfield', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 471,'Smooth Collie', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 472,'Smooth Fox Terrier', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 473,'Soft-coated Wheaten Terrier', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 474,'South Russian Ovcharka', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 475,'Spanish Mastiff', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 476,'Spanish Water Dog', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 477,'Spino degli Iblei', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 478,'Spinone Italiano', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 479,'Sporting Lucas Terrier', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 480,'St. Bernard', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 481,'St. Hubert Jura Hound', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 482,'Stabyhoun', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 483,'Staffordshire Bull Terrier', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 484,'Standard Schnauzer', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 485,'Stephens Stock', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 486,'Styrian Coarse-haired Hound', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 487,'Sussex Spaniel', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 488,'Swedish Lapphund', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 489,'Swedish Vallhund', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 490,'Taigan', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 491,'Taiwan Dog', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 492,'Tamaskan Dog', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 493,'Tang Dog', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 494,'Tarsus çatalburun', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 495,'Tatra Shepherd Dog', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 496,'Tazy', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 497,'Teddy Roosevelt Terrier', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 498,'Telomian', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 499,'Tenterfield Terrier', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 500,'Thai Bangkaew Dog', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 501,'Thai Ridgeback', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 502,'Tibetan Kyi Apso', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 503,'Tibetan Mastiff', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 504,'Tibetan spaniel', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 505,'Tibetan Terrier', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 506,'Tonya Finosu', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 507,'Tornjak', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 508,'Tosa', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 509,'Toy Fox Terrier', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 510,'Toy Manchester Terrier', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 511,'Transylvanian Hound', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 512,'Treeing Cur', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 513,'Treeing Feist', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 514,'Treeing Tennessee Brindle', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 515,'Treeing Walker Coonhound', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 516,'Trigg Hound', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 517,'Tyrolean Hound', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 518,'Valencian Terrier', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 519,'Vikhan', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 520,'Villano de Las Encartaciones', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 521,'Villanuco de Las Encartaciones', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 522,'Vizsla', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 523,'Volkosob', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 524,'Volpino Italiano', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 525,'Weimaraner', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 526,'Welsh Hound', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 527,'Welsh Sheepdog', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 528,'Welsh Springer Spaniel', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 529,'Welsh Terrier', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 530,'West Country Harrier', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 531,'West Highland White Terrier', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 532,'West Siberian Laika', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 533,'Westphalian Dachsbracke', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 534,'Wetterhoun', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 535,'Whippet', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 536,'White Shepherd', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 537,'White Swiss Shepherd Dog', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 538,'Wire Fox Terrier', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 539,'Wirehaired Pointing Griffon', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 540,'Wirehaired Vizsla', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 541,'Xiasi Dog', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 542,'Xoloitzcuintle', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 543,'Yakutian Laika', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 544,'Yorkshire Terrier', 1, 1);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 545,'Zerdava', 1, 1);

INSERT INTO ptts_breeds(id, description,state,species_id) values ( 546,'Abisinio', 1, 2);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 547,'American Curl', 1, 2);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 548,'Azul ruso', 1, 2);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 549,'American shorthair', 1, 2);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 550,'American wirehair', 1, 2);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 551,'Angora turco', 1, 2);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 552,'Africano doméstico', 1, 2);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 553,'Bengala', 1, 2);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 554,'Bobtail japonés', 1, 2);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 555,'Bombay', 1, 2);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 556,'Bosque de Noruega', 1, 2);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 557,'Brazilian Shorthair', 1, 2);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 558,'Brivon de pelo corto', 1, 2);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 559,'Brivon de pelo largo', 1, 2);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 560,'British Shorthair', 1, 2);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 561,'British Longhair', 1, 2);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 562,'Burmés', 1, 2);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 563,'Burmilla', 1, 2);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 564,'Cornish rex', 1, 2);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 565,'California Spangled', 1, 2);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 566,'Cymric', 1, 2);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 567,'Chartreux', 1, 2);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 568,'Curl Americano', 1, 2);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 569,'Devon rex', 1, 2);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 570,'Dorado africano', 1, 2);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 571,'Don Sphynx', 1, 2);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 572,'Dragon Li', 1, 2);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 573,'Gato común europeo', 1, 2);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 574,'Exótico de pelo corto', 1, 2);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 575,'gato elfo', 1, 2);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 576,'FoldEx', 1, 2);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 577,'German Rex', 1, 2);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 578,'Habana brown', 1, 2);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 579,'Himalayo', 1, 2);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 580,'Korat', 1, 2);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 581,'Khao Manee', 1, 2);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 582,'Manx', 1, 2);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 583,'Mau egipcio', 1, 2);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 584,'Munchkin', 1, 2);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 585,'Ocicat', 1, 2);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 586,'Oriental', 1, 2);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 587,'Oriental de pelo largo', 1, 2);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 588,'Persa americano o moderno', 1, 2);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 589,'Peterbald', 1, 2);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 590,'Pixie Bob', 1, 2);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 591,'Gato rojo', 1, 2);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 592,'Ragdoll', 1, 2);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 593,'Sagrado de Birmania', 1, 2);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 594,'Savannah', 1, 2);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 595,'Scottish Fold', 1, 2);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 596,'Selkirk rex', 1, 2);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 597,'Serengeti', 1, 2);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 598,'Seychellois', 1, 2);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 599,'Siamés', 1, 2);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 600,'Siamés Moderno', 1, 2);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 601,'Siamés Tradicional', 1, 2);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 602,'Siberiano', 1, 2);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 603,'Snowshoe', 1, 2);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 604,'Sphynx', 1, 2);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 605,'Tonkinés', 1, 2);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 606,'Toyger', 1, 2);
INSERT INTO ptts_breeds(id, description,state,species_id) values ( 607,'Van Turco', 1, 2);


